---
title: "carolinaAnalysis"
author: '@carolinanobre'
date: "9/3/2019"
output: html_document
fig_width: 12 
fig_height: 4 
---

## Setup

```{r setup}
library(tidyverse)
library(ggridges)
library(pwr) 
library(grid)
library(gtable)

library(ggthemes)

library(ggbeeswarm)

library(tidybayes)
library(cowplot)
library(broom)
library(Hmisc)

theme_set(theme_tidybayes() + panel_border() + background_grid())


#df <- read.csv("../results/pilot/CSV/TidyR.csv")
df <- read.csv("../results/study/CSV/TidyR.csv")
dfp <- read.csv("../results/study/CSV/participantInfoTidyR.csv")

dfc <- read.csv("../results/study/MaxQDA/codesTidy.csv")

wilcox <- read.csv("../results/study/CSV/wilcox.csv")



```


``` {r}
visType.colors <- c(adjMatrix = "#05b4dd", nodeLink = "#f4aa4a")

```


```{r}

data <- 
  dfc %>%
  group_by(Code,visType) %>%
  count()

data <-mutate(data,type=ifelse(grepl("topology-attribute", Code), "topology-attribute",
                               ifelse(grepl("topology", Code), "topology",
                                      ifelse(grepl("attribute", Code), "attribute", "Other")))) 


#data$n

#data$Code <- factor(data$Code, levels = data$Code[order(data$n)])



ggplot(data=data, aes(x=visType, y=n, fill=visType)) +
  geom_bar(stat="identity")+
   facet_grid(Code ~ .)+
  theme(strip.text.y = element_text(angle=0))+

    #theme_tufte()+
  #theme(axis.text.x=element_text(angle = -90, hjust = 0))+
  #theme(axis.text.y=element_text(angle = -90, hjust = 0))+

  
  coord_flip()+
  ylab("Code Frequency")+
  scale_fill_manual(values=visType.colors)
  
```


## Data Cleaning / Types

```{r}

df_acc <- df %>% 
  filter(measure=="accuracy") 

df_acc$value = as.numeric( as.character(df_acc$value ))


df_acc
```

```{r}
df %>% 
  filter(measure=="accuracy") %>% 
  mutate( value = as.numeric( as.character(value)) ) %>% 
  ggplot( aes(x=value, y=taskId) ) +
    geom_density_ridges() +
    facet_grid(. ~ visType)

```

```{r}

df_acc <- df %>% 
  filter(measure=="accuracy") 

df_acc$value = as.numeric( as.character(df_acc$value ))


df_time<- df %>% 
  filter(measure=="minutesOnTask") 

df_time$value = as.numeric( as.character(df_time$value ))


newFrame <- merge(df_time,df_acc, by="prolificId")

#newFrame

ggplot(newFrame, aes(x = value.x, y = value.y)) +
    geom_point(aes(color=visType.y))+
    facet_grid (visType.y ~taskId.y) +
    xlab("Time") +
    ylab("Accuracy")

ggsave(paste("charts/time_vs_accuracy_horizontal.pdf", sep=""), width = 35, height =3, units = "in")

```


```{r}

experience <- mutate(filter(dfp,measure=="visExperience"), visExperience = ifelse(as.numeric( as.character(value)) <3, "low (1-2)",
                                     ifelse(as.numeric( as.character(value))<6, "medium (3-5)", "high (6-7)"))) 
acc <- mutate( filter(dfp,measure=="averageAccuracy"), avgAcc = round(as.numeric(as.character(value)),digits=2) ) 

time <- mutate( filter(dfp,measure=="minutesOnTask"), timeValue = round(as.numeric(as.character(value)),digits=2) ) 

vis_type <- unique(select(df,"prolificId","visType"))


newFrame <- merge(experience,acc, by="prolificId")

newFrame <- merge(newFrame,vis_type, by="prolificId")

newFrame <- merge(newFrame,time, by="prolificId")


newFrame$visExperience <- factor(newFrame$visExperience, levels= c("low (1-2)","medium (3-5)","high (6-7)"))




#ggplot(newFrame, aes(x = timeValue, y = avgAcc)) +
#    geom_point(aes(color=visType))+
#    facet_grid(visType ~ .) +
#    xlab("Time") +
#    ylab("Average Accuracy")


ggplot(newFrame, aes(x = visType, y = avgAcc)) +
      #geom_beeswarm(priority='random', cex=4,alpha=0.3,size=3,aes(color=visType)) +
    geom_point(aes(color=visType,alpha=0.5,size=3))+

    facet_grid(. ~ visExperience) +
  stat_summary(fun.data = "mean_cl_boot", colour = "black", size = 0.5, alpha=1) +
    xlab("vis experience") +
    ylab("mean accuracy")


ggplot(newFrame, aes(x = visType, y = timeValue)) +
      #geom_beeswarm(priority='random',cex=4,alpha=0.3,size=3,aes(color=visType)) +

    geom_point(aes(color=visType,alpha=0.5,size=3))+
    facet_grid(. ~ visExperience) +
  stat_summary(fun.data = "mean_cl_boot", colour = "black", size = 0.5, alpha=1) +
    xlab("vis experience") +
    ylab("time")

```


```{r}

dfp %>% 
  filter(measure == "age") %>% 
  mutate( value = as.numeric( as.character(value)) ) %>% 
  ggplot(aes(x="age", y=value)) +
    geom_beeswarm(priority='density',cex=2, alpha=.6) +
  coord_flip() +
  xlab("") + ylab("")


histogramFunc <- function(var) {
data<- filter(dfp,measure == var) 
  ggplot(data=data, aes(data$value)) + 
    geom_histogram(stat="count") +
    xlab(var) 

    ggsave(paste("charts/",var,".pdf", sep=""), width = 7, height = 2, units = "in")
}

histogramFunc("age");
histogramFunc("browser");
histogramFunc("sex");
histogramFunc("degree");
histogramFunc("visExperience");


```


```{r}

labels.measure <- c(
  "minutesOnTask"  = "Time (minutes)",
  "accuracy"= "Accuracy",
  "difficulty"= "Difficulty",
  "confidence" = "Confidence"
)

labels.visType <- c(nodeLink = 'NL', adjMatrix = 'AM');


```



```{r, fig.width=5, fig.height=2} 


vplot <- function(task) {

sdf = df %>% filter( taskId == task )
tt = as.character(sdf[1,]$taskTitle)
prompt = as.character(sdf[1,]$taskPrompt)
number = as.character(sdf[1,]$taskNumber)

stats = wilcox %>% filter( taskNumber == number )
 
gridLines <- function(x) { 
  if (max(x) < 2) seq(0, 1, .25) 
  else if (max(x) == 7.3) seq (1,7,2)
    else seq(0,6,2) 
}

axisRange <- function(x) { 
  if (max(x) < 2) c(0, 1) 
  else if (max(x) == 7) c(1,7)
    else c(0,6) 
}

gridLabels <- function(x) { 
  if (max(as.numeric(x)) < 1.1) seq(0, 1, .5) 
  else if (max(as.numeric(x)) == 7.3) seq (1,7,2)
    else seq(0, 5,1 )
    #else seq(0, round(max(x)), round(max(x)/3)) 
}



plotData <-df %>% 
  filter( measure == "accuracy" | measure == "minutesOnTask" #)  %>% 
             | measure == "difficulty" | measure == "confidence") %>% 
    filter( taskId == task ) %>% 
  mutate( value = as.numeric( as.character(value)) ) %>% 
   mutate( label = labels.measure[as.character(measure)] ) %>% 
     mutate( visLabel = labels.visType[as.character(visType)] ) %>% 

  mutate( label = factor(label, levels=c("Accuracy","Time (minutes)", "Confidence","Difficulty")));



  ggplot(data=plotData, aes(x=visLabel, y=value, fill=visType, color=visType)) +
    facet_wrap(. ~ label, scales="free_x", nrow=1) +
    geom_violin(show.legend=FALSE) +
    stat_summary(fun.data = "mean_cl_boot", colour = "black", size = 0.5, alpha=.5, show.legend=FALSE) +
  coord_flip() + 
    labs(
      title = paste(number, '-', tt),
      subtitle = prompt,
      caption = paste('W = ',stats$W,' p-value = ',stats$'p.value' )
    )+
    theme ( plot.caption = element_text(hjust = 0, vjust =5,  face = "italic")) + 
    xlab ("") + 
    ylab("")+
    scale_fill_manual(values=visType.colors)+
    scale_color_manual(values=visType.colors)+      
    scale_y_continuous(breaks = gridLines, limits = axisRange) #,labels = gridLabels) 





#ggsave(paste("violins/",task,".pdf", sep=""), width = 10, height = 2.5, units = "in")
ggsave(paste("violins/",gsub(" ", "", paste(number,tt), fixed = TRUE),"_conf_diff.pdf", sep=""), width = 10, height = 2.5, units = "in")

}


vplot("S-task01")
vplot("S-task02")
vplot("S-task03")
vplot("S-task04")
vplot("S-task05")
vplot("S-task06")
vplot("S-task07")
vplot("S-task08")
vplot("S-task09")
vplot("S-task10")
vplot("S-task11")
vplot('S-task12')
vplot('S-task12A')
vplot('S-task12B')
vplot("S-task13")
vplot("S-task14")
vplot("S-task15")
vplot("S-task16")

  
```

``` {r fig.width=10, fig.height=16}

plotData <-df %>% 
  filter( measure == "accuracy" | measure == "minutesOnTask" | 
            measure == "difficulty" | measure == "confidence") %>% 
   # filter( taskId == task ) %>% 
  mutate( value = as.numeric( as.character(value)) ) %>% 
   mutate( label = labels.measure[as.character(measure)] ) %>% 
     mutate( visLabel = labels.visType[as.character(visType)] ) %>% 

  mutate( label = factor(label, levels=c("Accuracy","Time (minutes)", "Confidence","Difficulty")));

  ggplot(data=plotData, aes(x=visLabel, y=value, fill=visType, color=visType)) +
    facet_grid(taskId ~ label, scales="free_x") +
    geom_violin(show.legend=FALSE) +
    stat_summary(fun.data = "mean_cl_boot", colour = "black", size = 0.5, alpha=.75, show.legend=FALSE) +
  coord_flip() + 
    scale_fill_manual(values=visType.colors)+
    scale_color_manual(values=visType.colors)     
  #scale_y_continuous(breaks = gridLines) #,labels = gridLabels) 

```


``` {r, fig.width=8, fig.height=2}

vplot("S-task02")
vplot("S-task03")
vplot("S-task04")
vplot("S-task05")
vplot("S-task06")
vplot("S-task07")
vplot("S-task08")
vplot("S-task09")
vplot("S-task10")
vplot("S-task11")
vplot('S-task12')
vplot('S-task12A')
vplot('S-task12B')
vplot("S-task13")
vplot("S-task14")
vplot("S-task15")
vplot("S-task16")

```

